### PR TITLE
Fixed compilation error

### PR DESCRIPTION
**Pull request by gmargari**

### CODE REVIEW

**Comment by seancribbs** [comment]
On most platforms, `size_t` is an alias for `unsigned int` or `unsigned long` (and generally safer across platforms). What compile error do you get?

**Comment by gmargari** [comment]
The error I get is:
error: invalid conversion from ‘size_t\* {aka unsigned int_}’ to ‘long unsigned int_’ [-fpermissive]

**Comment by seancribbs** [comment]
What platform are you compiling on?

**Comment by gmargari** [comment]
Ubuntu 14.04.1 (32bit), with gcc 4.8.2

**Comment by seancribbs** [comment]
Aha! We don't support compiling on 32-bit platforms anymore. Some of LevelDB's internal features require 64-bit. /cc @matthewvon

**Comment by gmargari** [comment]
Hm, I didn't see this constrain anywhere. I have been developing code in LevelDB for about a year now and didn't find anything related. Is this an erlang-leveldb integration issue?

**Comment by seancribbs** [comment]
We have deep customizations of the LevelDB codebase, see [our fork](/basho/leveldb). Aside from that, I cannot comment on details except that we stopped supporting 32-bit for various reasons over a year ago.

**Comment by gmargari** [comment]
I see. Thanks.

**Pull request closed without merging**
