### PR TITLE
Bumped leveldb version to pick up sequential tunings [JIRA: RIAK-1928]

### PR DESCRIPTION
**Pull request by jonmeredith**
Internal reference zd://9122

### CODE REVIEW

**Comment by engelsanchez** [comment]
+1  b544b75

I picked some fluff from my belly button, and it all looked good.

**Comment by jonmeredith** [comment]
@borshop merge

**Comment by jonmeredith** [comment]
@borshop merge

**Comment by DSomogyi** [comment]
create jira issue

**Pull request merged**
