### PR TITLE
Export iterator/3 so users can iterate over just keys

### PR DESCRIPTION
**Pull request by reiddraper**
I've been playing with leveldb iterators (not through `eleveldb:fold`), and would find it useful to be able to iterator through keys only. I don't know if there's a better way to deal with the 3rd argument to `iterator` only being able to be `keys_only`. If you pass in some other atom, it doesn't blow up, but just silently ignores that arg.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Don't see any problem with this. +1 to merge.

**Comment by dreverri** [comment]
What happened to this change? This export is no longer available.

**Comment by reiddraper** [comment]
@dreverri looks like some kind of commit-undo mistake in 025a3602a55845d1f4f3940158a627772d4e9bd0

**Comment by reiddraper** [comment]
cc @matthewvon ^

**Pull request merged**
