### PR TITLE
Mv tiered options

### PR DESCRIPTION
**Pull request by matthewvon**
Add options necessary to support tiered storage based upon the sst_? directories (introduced in Riak 1.3).

Branch discussion is here:
    https://github.com/basho/leveldb/wiki/mv-tiered-options

Merge Requirements
- [ ] Eng +1
- [x] CSE +1
- [x] ProdMgmt + 1

### CODE REVIEW

**Comment by joedevivo** [comment]
The configuration options added for tiered storage are:

``` properties
leveldb.tiered = 2
leveldb.tiered.mountpoint.fast = /mnt/speedy
leveldb.tiered.mountpoint.slow = /mnt/slowpoke
```

**Comment by jmshoffs0812** [comment]
CSE +1

**Comment by jonmeredith** [comment]
Mountpoints aren't supposed to be raw devices are they?

On Thu, Apr 10, 2014 at 9:26 AM, Joe DeVivo notifications@github.comwrote:

> The configuration options added for tiered storage are:
> 
> leveldb.tiered = 2
> leveldb.tiered.mountpoint.fast = /dev/speedy
> leveldb.tiered.mountpoint.slow = /dev/slowpoke
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/basho/eleveldb/pull/111#issuecomment-40099340
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by joedevivo** [comment]
oh, @jonmeredith good point, no those are supposed to be paths

**Comment by gburd** [comment]
I'm not in love with "mountpoint" rather than "path", that seems contrived.  If the thought is to nudge admins to use an entire device I'm not sure this is going to do that, but I am sure it'll cause confusion.  If this is a pattern in our config, I'd rather change it then replicate it here.

I'm also not sure I get what the "2" in "leveldb.tiered = 2" is supposed to mean.  Maybe "leveldb.tiered = yes; leveldb.tiered.split_after.level = 2" or something more descriptive.

**Comment by gburd** [comment]
Here is an idea to consider for naming of these options, but if this is too complex we should just go with what we had started to consider in this thread.

For a 2 tier setup with [0-2) as the fast/first tier and [2-6] as the slower tier.
leveldb.tiered = yes
leveldb.tiered.2.path = /storage/speedy-flash-drive
leveldb.path = /storage/slower-raid-of-spinning-disks

For a non-tiered setup.
leveldb.tiered = no <- optional to even have this in the config at all, default is "no"
leveldb.path = /a/path/relative/to/data-dir/leveldb

For a 3 tier setup with [0-2) as the fast/first tier and [2-6) as the second tier and [6-6] as the last tier.
leveldb.tiered = yes
leveldb.tiered.2.path = /storage/speedy-flash-drive
leveldb.tiered.6.path = /storage/slower-raid-of-spinning-disks
leveldb.path = /storage/somewhere-else

**Comment by gburd** [comment]
Due to time constraints, let's go with the orig idea already +1'ed by others.

PM +1

**Comment by joedevivo** [comment]
new verison

``` properties
leveldb.tiered = 2
leveldb.tiered.path.fast = /mnt/speedy
leveldb.tiered.path.slow = /mnt/slowpoke
```

**Comment by joedevivo** [comment]
I approve @matthewvon's C related changes for this PR

**Comment by gburd** [comment]
PM +1

**Comment by matthewvon** [comment]
+1 to Joe's cuttlefish edits.

**Pull request merged**
