### PR TITLE
remove a long-unused module eleveldb_ts

### PR DESCRIPTION
**Pull request by hmmr**
because it's dead, Jim.

### CODE REVIEW

**Comment by erikleitch** [comment]
+1 111617a

eleveldb_ts is dead.  Да здравствует eleveldb_ts!

**Comment by hmmr** [comment]
@borshop merge

**Comment by hazen** [comment]
Weirdly it does not seem to have lager

```
src/eleveldb.erl:321: Warning: eleveldb:do_streaming_fold/3 calls undefined function lager:error/2 (Xref)
ERROR: xref failed while processing /home/buildbot/masters/riak/test-eleveldb/build: rebar_abort
make: *** [xref] Error 1
```

```
==> build (dialyzer)
  Checking whether the PLT /home/buildbot/.combo_dialyzer_plt is up-to-date... yes
  Checking whether the PLT .local_dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
eleveldb.erl:324: Call to missing or unexported function lager:error/2
```

**Comment by hmmr** [comment]
@javajolt This PR effectively requires #192 to enable lager_transform and make `lager:error` available to dialyzer.

**Comment by hazen** [comment]
Cool:

```
make: *** [test] Bus error (core dumped)
```

**Comment by hazen** [comment]
```
ERROR: sh(cc c_src/CmpUtil.o c_src/DataType.o c_src/Encoding.o c_src/ErlUtil.o c_src/StringBuf.o c_src/cmp.o c_src/cmp_mem_access.o c_src/eleveldb.o c_src/extractor.o c_src/filter_parser.o c_src/refobjects.o c_src/workitems.o  -shared  -L"/opt/basho/installs/erlang/R16B02basho10-OTP_R16B02_basho10/lib/erl_interface-3.7.14/lib" -lerl_interface -lei c_src/leveldb/libleveldb.a c_src/system/lib/libsnappy.a -lstdc++ -o priv/eleveldb.so)
failed with return code 1 and the following output:
collect2: ld returned 1 exit status

ERROR: compile failed while processing /home/buildbot/masters/riak/test-eleveldb/build: rebar_abort
make: *** [compile] Error 1
```

**Comment by hmmr** [comment]
@borshop: retry 5a0c26e

**Pull request merged**
