### PR TITLE
Dss compaction tweaks

### PR DESCRIPTION
**Pull request by dizzyd**
Revamped build process for leveldb (to switch _back_ to our own git repo), plus commits necessary to get LevelDB compaction to not block for long periods of time

### CODE REVIEW

**Comment by massung** [comment]
Not sure if you care since it's a call into the leveldb c++ code, but a bogus repair call still returns 'ok' regardless:

```
eleveldb:repair("dataasdfasdf",[this,means,nothing]).
== ok
```

If this is ever meant to be available externally (via REST API or PBC, etc) then I think this would be confusing to users.

**Comment by dizzyd** [comment]
That result should be based on check the result of the LevelDB call -- if LevelDB is returning status.ok, there's not much else to report. :)

This is a pretty low-level (and drastic) call to LevelDB; I don't anticipate it being externally invocable.

**Comment by massung** [comment]
Aside from the passing an invalid directory returning 'ok', seems good. +1.

**Comment by jonmeredith** [comment]
+1 merge

**Pull request merged**
