### PR TITLE
multibackend part of .schema belongs into riak_kv

### PR DESCRIPTION
**Pull request by joedevivo**
Hi I think the multibackend part of the .schema file does not belong into the eleveldb.schema file. It's specific to riak_kv and not to this library so I think it would belong there.

This can of cause be argued given eleveldb was developed for riak_kv but still for library users it would make more sense to keep those separated.

An alternative would be having two .schema files one eleveldb.schema and one eleveldb_multi.schema

### CODE REVIEW

**Comment by jrwest** [comment]
funny you should ask, it just came back up today cc/ @joedevivo

**Comment by matthewvon** [comment]
Part of the answer is simple.  If you move the parallel settings of multibackend to another repo / location, they will not be maintained.  Either parallel has to be eliminated, or kept here.

**Comment by jrwest** [comment]
imo, the fundamental problem is that the settings need to be duplicated, rather than only being defined once and "included" into the multi-backend as "subconfigs". That's not something thats supported right now though, so they should live in the same repo.

**Comment by joedevivo** [comment]
I'm working on a bug in the bitcask multi_backend schema, in which I'll try to accommodate this same issue. If we like the solution, I'll port it to leveldatabass

**Comment by joedevivo** [comment]
Check out how I handled it in basho/bitcask#157

**Comment by joedevivo** [comment]
The above is the application of the solution used in basho/bitcask#157

**Comment by matthewvon** [comment]
is schema_tests verifying that all items in eleveldb schema are in eleveldb_multi schema?  my erlang sucks.

**Comment by joedevivo** [comment]
@matthewvon yup, and that they're properly overridden with multi versions of the defaults if necessary

**Comment by jrwest** [comment]
+1 merge. builds and tests pass. Like https://github.com/basho/bitcask/pull/157 Riak & EE will need to have the new schema's incorporated into the build for this all to work.

**Pull request merged**
