### PR TITLE
Depend on system snappy

### PR DESCRIPTION
**Pull request by hmmr**
Rather than downloading and building snappy, depend on libsnappy preinstalled on the host system.

Also, use `--depth=1` when cloning leveldb.

### CODE REVIEW

**Comment by codeadict** [comment]
I'm getting ` ld: library not found for -lsnappy` on an ARM mac by installing snappy from homebrew. I'll do more investigation this weekend but seems like the problem doesn't get fixed for OSX

**Comment by ioolkos** [comment]
@codeadict I think we had a couple of commits over at the VerneMQ fork, related to building on FreeBSD and Darwin. Not sure this is directly related, but maybe there's some stuff useful to upstream or cherrypick. https://github.com/vernemq/eleveldb/pull/10

**Comment by hmmr** [comment]
For the record, on FreeBSD-13.1, after `pkg install snappy`, it is required to `export LDFLAGS=-L/usr/local/lib` before running `make`.

**Comment by hmmr** [comment]
Closing, in favor of #272.

**Comment by hmmr** [comment]
Closing, in favor of #272.

**Pull request closed without merging**
