### PR TITLE
Mv compress option

### PR DESCRIPTION
**Pull request by matthewvon**
Bring the compression option to cuttlefish.  Developers want it (namely Matthew) and customers on mailing list are talking about how they disable compression in favor of ZFS compression.  This needs to be available.

### CODE REVIEW

**Comment by michellep-basho** [comment]
+1 from Product

**Comment by angrycub** [comment]
+1 CSE

**Comment by joedevivo** [comment]
this should be unit tested.

**Comment by joedevivo** [comment]
Did a `make clean`, then a `make compile` and pulled all new deps. this branch isn't building for me:

```
Compiling c_src/eleveldb.cc
c_src/eleveldb.cc:334:26: error: no member named 'block_cache_threshold' in 'leveldb::Options'
                    opts.block_cache_threshold = memory_sz;
                    ~~~~ ^
1 error generated.
ERROR: compile failed while processing /Users/joe/dev/basho/eleveldb: rebar_abort
make: *** [compile] Error 1
```

**Comment by matthewvon** [comment]
rm -rf c_src/leveldb
make
make test

not my fault rebar is trash.

**Comment by joedevivo** [comment]
+1, thanks!

**Pull request merged**
