### PR TITLE
BSD support

### PR DESCRIPTION
**Pull request by Vagabond**
These patches make it possible to compile eleveldb on FreeBSD, NetBSD, OpenBSD and DragonFlyBSD. All the eunit tests pass and 'make check' for leveldb passes everywhere except for OpenBSD.

Unfortunately, because BSD make (except on FreeBSD) don't support the -C option, you need to tweak the rebar.config to call gmake instead. I don't know of a clean solution to this issue.

### CODE REVIEW

**Comment by ArtemGr** [comment]
> Unfortunately, because BSD make (except on FreeBSD) don't support the -C option,
> you need to tweak the rebar.config to call gmake instead. I don't know of a clean solution to this issue.

Hi!
The usual way to deal with this is to use the ${MAKE} variable. That way, the user uses "gmake" at the top level (or the port maintainer uses "gmake" from the port makefiles, which is pretty common) and it is propagated down the compile chain.

**Comment by Vagabond** [comment]
Yes, except that in this case we're not guranteed to have $MAKE set, eg. if the user compiles at the toplevel via './rebar compile' instead of 'make'. Also, rebar doesn't seem to allow you access to $MAKE inside the pre-compile hook.

**Comment by ArtemGr** [comment]
You already using a stub Makefile which calls gmake. Now, if that stub Makefile would use ${MAKE} (which is always available in a Makefile) then the whole thing would be Linux-compatible. FreeBSD users will just have to type 'MAKE=gmake ./rebar compile' instead of './rebar compile'. Just a thought.

**Comment by Vagabond** [comment]
Rebased on top of master with gmake/make compatibility fixes.

**Comment by Vagabond** [comment]
Pending the leveldb changes being merged upstream this pull request is in limbo:

http://code.google.com/p/leveldb/issues/detail?id=59

**Comment by Vagabond** [comment]
This is stale and has been mostly resolved upstream now.

**Pull request closed without merging**
