### PR TITLE
added explicit close function

### PR DESCRIPTION
**Pull request by moonpolysoft**
Needed the ability to close a database independent of NIF cleanup / beam GC.

### CODE REVIEW

**Comment by dizzyd** [comment]
Generally, this needs some bullet-proofing:
- If the handle can be deleted, all operations which use it should check for deletion before executing
- I think the handle may need to be ref-counted for proper behavior while it's also in-use for an iterator (??)

It would be extremely handy to have this functionality, though. Thanks! :)

**Comment by moonpolysoft** [comment]
Added the necessary bulletproofing.  Any nif call on a closed database will badarg, and if there are outstanding iterators against a database then the call to close will badarg.

**Comment by moonpolysoft** [comment]
Bump.

**Comment by dizzyd** [comment]
Hi @cliffmoon, I'm pretty sure there are locking issues remaining in this code but haven't had a chance to dig into it. The API was, IIRC, safe to use across multiple processes, but with the addition of the close I think that safety is bjorked. Happy to be proven wrong. :)

**Comment by dizzyd** [comment]
FWIW, I'm hoping to take a gander at this prior to our next Riak release.  Haven't forgotten...just bogged down. Lots of good LevelDB performance improvements on this way. :)

**Comment by seancribbs** [comment]
@cliffmoon Looks like the explicit close function made it in during the Riak 1.2 release cycle. Closing this PR.

**Pull request closed without merging**
