### PR TITLE
We're using eleveldb in an escript

### PR DESCRIPTION
**Pull request by elbrujohalcon**
I know it's not the best solution, but it was enough for what we needed and, since it wasn't even working before... you may want to merge it.

### CODE REVIEW

**Comment by dizzyd** [comment]
I'm happy to accept patches for the specs, but the code to load the .so from the escript won't work. Dynamic library loading code typically requires (at the operating system level) a file to be present in the filesystem so that it can memory-map the code into the process space.

**Comment by elbrujohalcon** [comment]
I know, that's why in our last try we placed the .so file right next to escript. That is, just ../eleveldb.so instead of ../priv/eleveldb.so

**Comment by dizzyd** [comment]
Sorry to leave this PR open so long. If you adjust the init/0 code to copy the file into a temporary path and load from there, I'll be happy to accept this patch. If you're no longer interested in this patch, let me know and I can close out the PR.

**Comment by matthewvon** [comment]
Is this issue still valid / open?  Or should I close it?

**Pull request closed without merging**
